//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34011
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace remotecontrolclient.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("remotecontrolclient.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remote Control PC required installed on the computer RC SERVER. 
        ///You can download it from the site ALEXSOFT.IN.
        /// </summary>
        public static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program is designed to control your PC from your smartphone via a shared Wi-Fi network. Remote controls playback of movies, music, photos, TV tuner &apos;Behold TV&apos;. Is a function of scan, sort and search your media files..
        /// </summary>
        public static string about2 {
            get {
                return ResourceManager.GetString("about2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Albums.
        /// </summary>
        public static string albums {
            get {
                return ResourceManager.GetString("albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All album.
        /// </summary>
        public static string allalbum {
            get {
                return ResourceManager.GetString("allalbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All folder.
        /// </summary>
        public static string allfolder {
            get {
                return ResourceManager.GetString("allfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All IP (UDP).
        /// </summary>
        public static string allip {
            get {
                return ResourceManager.GetString("allip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All track random.
        /// </summary>
        public static string allrandom {
            get {
                return ResourceManager.GetString("allrandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full scan.
        /// </summary>
        public static string allscan {
            get {
                return ResourceManager.GetString("allscan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All track.
        /// </summary>
        public static string alltrack {
            get {
                return ResourceManager.GetString("alltrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на REMOTE CONTROL PC.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Artist.
        /// </summary>
        public static string artist {
            get {
                return ResourceManager.GetString("artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Artist.
        /// </summary>
        public static string artists {
            get {
                return ResourceManager.GetString("artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio files.
        /// </summary>
        public static string audiofile {
            get {
                return ResourceManager.GetString("audiofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto code.
        /// </summary>
        public static string autocode {
            get {
                return ResourceManager.GetString("autocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cat.
        /// </summary>
        public static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на channel selection.
        /// </summary>
        public static string channel {
            get {
                return ResourceManager.GetString("channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you shure you want to delete?.
        /// </summary>
        public static string deletephoto {
            get {
                return ResourceManager.GetString("deletephoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleting a file.
        /// </summary>
        public static string delfile {
            get {
                return ResourceManager.GetString("delfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove the film?.
        /// </summary>
        public static string delmovies {
            get {
                return ResourceManager.GetString("delmovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Drive.
        /// </summary>
        public static string driveselect {
            get {
                return ResourceManager.GetString("driveselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dubai.
        /// </summary>
        public static string dubai {
            get {
                return ResourceManager.GetString("dubai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorite.
        /// </summary>
        public static string fav {
            get {
                return ResourceManager.GetString("fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder.
        /// </summary>
        public static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goa.
        /// </summary>
        public static string goa {
            get {
                return ResourceManager.GetString("goa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hibernate.
        /// </summary>
        public static string hibernate {
            get {
                return ResourceManager.GetString("hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP address.
        /// </summary>
        public static string ip {
            get {
                return ResourceManager.GetString("ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error connecting to server - invalid IP address of the server or on the PC is not running RC.
        /// </summary>
        public static string ipbad {
            get {
                return ResourceManager.GetString("ipbad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на incorrect IP address!.
        /// </summary>
        public static string ipnotcorret {
            get {
                return ResourceManager.GetString("ipnotcorret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lock scren (screensaver).
        /// </summary>
        public static string lockscreen {
            get {
                return ResourceManager.GetString("lockscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAC address.
        /// </summary>
        public static string mac {
            get {
                return ResourceManager.GetString("mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (For power ON PC).
        /// </summary>
        public static string mac2 {
            get {
                return ResourceManager.GetString("mac2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAC address is incorrect!.
        /// </summary>
        public static string macnotcorrect {
            get {
                return ResourceManager.GetString("macnotcorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 min.
        /// </summary>
        public static string min1 {
            get {
                return ResourceManager.GetString("min1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 min.
        /// </summary>
        public static string min10 {
            get {
                return ResourceManager.GetString("min10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 hours.
        /// </summary>
        public static string min120 {
            get {
                return ResourceManager.GetString("min120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.5 hours.
        /// </summary>
        public static string min150 {
            get {
                return ResourceManager.GetString("min150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 hours.
        /// </summary>
        public static string min180 {
            get {
                return ResourceManager.GetString("min180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 20 min.
        /// </summary>
        public static string min20 {
            get {
                return ResourceManager.GetString("min20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 min.
        /// </summary>
        public static string min3 {
            get {
                return ResourceManager.GetString("min3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 30 min.
        /// </summary>
        public static string min30 {
            get {
                return ResourceManager.GetString("min30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 45 min.
        /// </summary>
        public static string min45 {
            get {
                return ResourceManager.GetString("min45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 min.
        /// </summary>
        public static string min5 {
            get {
                return ResourceManager.GetString("min5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 hour.
        /// </summary>
        public static string min60 {
            get {
                return ResourceManager.GetString("min60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.5 hour.
        /// </summary>
        public static string min90 {
            get {
                return ResourceManager.GetString("min90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minsk.
        /// </summary>
        public static string minsk {
            get {
                return ResourceManager.GetString("minsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Music.
        /// </summary>
        public static string music {
            get {
                return ResourceManager.GetString("music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uncertain network error!.
        /// </summary>
        public static string networkerror {
            get {
                return ResourceManager.GetString("networkerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! Not enter correct IP address of server..
        /// </summary>
        public static string noip {
            get {
                return ResourceManager.GetString("noip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn Off Sleep Mode.
        /// </summary>
        public static string offtimer {
            get {
                return ResourceManager.GetString("offtimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One track.
        /// </summary>
        public static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Photo.
        /// </summary>
        public static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of photo.
        /// </summary>
        public static string photos {
            get {
                return ResourceManager.GetString("photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create playlist.
        /// </summary>
        public static string playlist {
            get {
                return ResourceManager.GetString("playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power Menu.
        /// </summary>
        public static string powermenu {
            get {
                return ResourceManager.GetString("powermenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на power OFF.
        /// </summary>
        public static string poweroff {
            get {
                return ResourceManager.GetString("poweroff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -=power ON=-.
        /// </summary>
        public static string poweron {
            get {
                return ResourceManager.GetString("poweron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reboot.
        /// </summary>
        public static string reboot {
            get {
                return ResourceManager.GetString("reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример значения свойства среды выполнения.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scan.
        /// </summary>
        public static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на shutdown.
        /// </summary>
        public static string shutdown {
            get {
                return ResourceManager.GetString("shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort media files by:.
        /// </summary>
        public static string sortby {
            get {
                return ResourceManager.GetString("sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Istanbul.
        /// </summary>
        public static string stambul {
            get {
                return ResourceManager.GetString("stambul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на standby.
        /// </summary>
        public static string standby {
            get {
                return ResourceManager.GetString("standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PC shutdown over:.
        /// </summary>
        public static string timeoff {
            get {
                return ResourceManager.GetString("timeoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timer menu.
        /// </summary>
        public static string timer {
            get {
                return ResourceManager.GetString("timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BACKGROUND.
        /// </summary>
        public static string topic {
            get {
                return ResourceManager.GetString("topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TV tuner Behold.
        /// </summary>
        public static string tv {
            get {
                return ResourceManager.GetString("tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 20.
        /// </summary>
        public static string versionprogram {
            get {
                return ResourceManager.GetString("versionprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vibro.
        /// </summary>
        public static string vibro {
            get {
                return ResourceManager.GetString("vibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video files.
        /// </summary>
        public static string videofile {
            get {
                return ResourceManager.GetString("videofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Videoplayer.
        /// </summary>
        public static string videoselect {
            get {
                return ResourceManager.GetString("videoselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vol. Lock.
        /// </summary>
        public static string volblock {
            get {
                return ResourceManager.GetString("volblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Volume control is disabled.
        /// </summary>
        public static string volmasteroff {
            get {
                return ResourceManager.GetString("volmasteroff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Master Volume.
        /// </summary>
        public static string volmenu {
            get {
                return ResourceManager.GetString("volmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! Phone is not connected to a Wi-Fi network.
        /// </summary>
        public static string wifinoconnect {
            get {
                return ResourceManager.GetString("wifinoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error! Wi-Fi network without the Internet.
        /// </summary>
        public static string wifinointernet {
            get {
                return ResourceManager.GetString("wifinointernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wi-Fi is OFF.
        /// </summary>
        public static string wifioff {
            get {
                return ResourceManager.GetString("wifioff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!  Wi-Fi is OFF. Need Wi-Fi for work..
        /// </summary>
        public static string wifiofferror {
            get {
                return ResourceManager.GetString("wifiofferror", resourceCulture);
            }
        }
    }
}
